version: '2.1'
services:
  kosmtik:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/openstreetmap-carto
      - openstreetmap-data:/var/lib/postgresql/data
    depends_on:
      - db
    ports:
      - "127.0.0.1:6789:6789"
    environment:
      - PGHOST=db
      - PGUSER=postgres
  db:
    image: db:v1
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - PG_SHARED_BUFFERS
      - PG_AUTOVACUUM
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    sysctls:
      kernel.shmmax: 268435456
    volumes:
      - openstreetmap-data:/var/lib/postgresql/data      
  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
    volumes:
      - .:/openstreetmap-carto
      - openstreetmap-data:/var/lib/postgresql/data
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - PG_SHARED_BUFFERS
      - PG_AUTOVACUUM      
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE
    sysctls:
      kernel.shmmax: 268435456      

volumes:
   openstreetmap-data:
    external: true
